export default [
  {
    id: 1,
    title: "Balance of mild",
    vidurl: "https://www.youtube.com/embed/FIIJddZYA-o?si=V3lKbTP624kJ2XXr",
    description: "The one best way of handling",
    views: 350,
    days: 6,
  },
  {
    id: 2,
    title: "Vintage of milean",
    vidurl: "https://www.youtube.com/embed/2sgPIAu3DGU?si=6kcmCvPa7PKgYPcS",
    description: "ready for the long run",
    views: 850,
    days: 5,
  },
  {
    id: 3,
    title: "Academical mind",
    vidurl: "https://www.youtube.com/embed/0ImdPaKBIQY?si=WRoABbj6GKOUhCgE",
    description:
      "Education is the one thing that gives you knowledge of everything",
    views: 60,
    days: 1,
  },
  {
    id: 4,
    title: "Engineering mindset",
    vidurl: "video4.mp4",
    description: "One way to show how the world structures came alive",
    views: 950,
    days: 10,
  },
  {
    id: 5,
    title: "Balance of time",
    vidurl: "https://www.youtube.com/embed/dS2Mt1_orSs?si=Cs9enPIejs9M_X5P",
    description: "Show the balance of mind and time and reality",
    views: 100,
    days: 1,
  },
  {
    id: 6,
    title: "The brain wave ",
    vidurl: "https://www.youtube.com/embed/XXYbVpkI-UY?si=AyB7zyO5ju5ePTzU",
    description: "How human reason and function with reality",
    views: 800,
    days: 2,
  },
  {
    id: 7,
    title: "Look of things",
    vidurl: "https://www.youtube.com/embed/EUTAdrLKLlI?si=CtU2qiclJ3HwETLZ",
    description: "How things are viewed is how they are qualified",
    views: 500,
    days: 20,
  },
  {
    id: 8,
    title: "The urge of success",
    vidurl: "https://www.youtube.com/embed/ISnxs-NlRYg?si=mSkfiY4VdFBJmvl6",
    description: "The eagerness to make it through anything possible",
    views: 180,
    days: 12,
  },
  {
    id: 9,
    title: "Balance of mild",
    vidurl: "https://www.youtube.com/embed/FIIJddZYA-o?si=V3lKbTP624kJ2XXr",
    description: "The one best way of handling",
    views: 350,
    days: 6,
  },
  {
    id: 10,
    title: "Vintage of milean",
    vidurl: "https://www.youtube.com/embed/2sgPIAu3DGU?si=6kcmCvPa7PKgYPcS",
    description: "ready for the long run",
    views: 850,
    days: 5,
  },
  {
    id: 11,
    title: "Academical mind",
    vidurl: "https://www.youtube.com/embed/0ImdPaKBIQY?si=WRoABbj6GKOUhCgE",
    description:
      "Education is the one thing that gives you knowledge of everything",
    views: 60,
    days: 1,
  },
  {
    id: 12,
    title: "Engineering mindset",
    vidurl: "video4.mp4",
    description: "One way to show how the world structures came alive",
    views: 950,
    days: 10,
  },
  {
    id: 13,
    title: "Balance of time",
    vidurl: "https://www.youtube.com/embed/dS2Mt1_orSs?si=Cs9enPIejs9M_X5P",
    description: "Show the balance of mind and time and reality",
    views: 100,
    days: 1,
  },
  {
    id: 14,
    title: "The brain wave ",
    vidurl: "https://www.youtube.com/embed/XXYbVpkI-UY?si=AyB7zyO5ju5ePTzU",
    description: "How human reason and function with reality",
    views: 800,
    days: 2,
  },
  {
    id: 15,
    title: "Look of things",
    vidurl: "https://www.youtube.com/embed/EUTAdrLKLlI?si=CtU2qiclJ3HwETLZ",
    description: "How things are viewed is how they are qualified",
    views: 500,
    days: 20,
  },
  {
    id: 16,
    title: "The urge of success",
    vidurl: "https://www.youtube.com/embed/ISnxs-NlRYg?si=mSkfiY4VdFBJmvl6",
    description: "The eagerness to make it through anything possible",
    views: 180,
    days: 12,
  },
  {
    id: 17,
    title: "Balance of mild",
    vidurl: "https://www.youtube.com/embed/FIIJddZYA-o?si=V3lKbTP624kJ2XXr",
    description: "The one best way of handling",
    views: 350,
    days: 6,
  },
  {
    id: 18,
    title: "Vintage of milean",
    vidurl: "https://www.youtube.com/embed/2sgPIAu3DGU?si=6kcmCvPa7PKgYPcS",
    description: "ready for the long run",
    views: 850,
    days: 5,
  },
  {
    id: 19,
    title: "Academical mind",
    vidurl: "https://www.youtube.com/embed/0ImdPaKBIQY?si=WRoABbj6GKOUhCgE",
    description:
      "Education is the one thing that gives you knowledge of everything",
    views: 60,
    days: 1,
  },
  {
    id: 20,
    title: "Engineering mindset",
    vidurl: "video4.mp4",
    description: "One way to show how the world structures came alive",
    views: 950,
    days: 10,
  },
  {
    id: 21,
    title: "Balance of time",
    vidurl: "https://www.youtube.com/embed/dS2Mt1_orSs?si=Cs9enPIejs9M_X5P",
    description: "Show the balance of mind and time and reality",
    views: 100,
    days: 1,
  },
  {
    id: 22,
    title: "The brain wave ",
    vidurl: "https://www.youtube.com/embed/XXYbVpkI-UY?si=AyB7zyO5ju5ePTzU",
    description: "How human reason and function with reality",
    views: 800,
    days: 2,
  },
  {
    id: 23,
    title: "Look of things",
    vidurl: "https://www.youtube.com/embed/EUTAdrLKLlI?si=CtU2qiclJ3HwETLZ",
    description: "How things are viewed is how they are qualified",
    views: 500,
    days: 20,
  },
  {
    id: 24,
    title: "The urge of success",
    vidurl: "https://www.youtube.com/embed/ISnxs-NlRYg?si=mSkfiY4VdFBJmvl6",
    description: "The eagerness to make it through anything possible",
    views: 180,
    days: 12,
  },
];
